### ISSUE TITLE
Repetitive boilerplate code in javascript file

### ISSUE THREAD

**Issue by pcraig3** [kevinmmcraig/kevinmmcraig.github.io#1]
Just a small point, but you can probably put [this stuff](https://github.com/kevinmmcraig/kevinmmcraig.github.io/blob/master/scripts/resume.js#L9-L24) into a loop rather than specifying each manually.

And you could probably use your javascript to get the number of buttons as well.

**Comment by kevinmmcraig** [comment]
I tried, but it has to be accessible at all times I think.  Putting it into a loop would render the buttons useless. That or it would open and close 5 times with one click of the button

**Comment by pcraig3** [comment]
Right, I hadn't really looked at it properly.

Here's another idea, using [CSS (partial) attribute selectors](https://css-tricks.com/attribute-selectors/) and [event delegation](http://stackoverflow.com/questions/8110934/direct-vs-delegated-jquery-on):

```javascript
$(".res_main_body").on("click", "[id^=toggleContent]", function() {
    $(this).parents(".heading").next(".content").slideToggle(speed="slow");
});
```

- `.parents(".class")` will keep going through parent elements until it finds one with a matching class
- `.next(".class")` will keep going through sibling elements (elements at the same level in the tree) until it finds one with a matching classname

Let me know if anything's unclear.

**Comment by kevinmmcraig** [comment]
Ok, that helps, thanks Paul!  I also calculated the speed variable to be proportional to the height of the content, because I felt the shorter content divs would open too slowly and the longer ones too quickly (the work experience compared to the core competencies buttons)
I'm going to close this issue now
